### ISSUE TITLE
未能加载X5内核

### ISSUE THREAD

**Issue by hejiajun107** [code-jar/TBS.Xamarin.Android#1]
好像没有成功加载，进入http://debugtbs.qq.com 合作方加载检测提示 未能加载X5内核，解决原因及办法：X5内核目前只提供32位so.......另外视频播放器和文件选择器显示的也不是x5浏览器的样子

**Comment by code-jar** [comment]
页面左上角红字展示的内核加载信息，如果X5内核加载成功会显示 X5 core。 Demo项目中已经把64位so文件包含进去了，首次安装应该可能没有正确加载 多打开几次就正常了，请保持网络访问正常
